// <auto-generated />
using CA2API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CA2API.Data.Migrations
{
    [DbContext(typeof(DogContext))]
    partial class DogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CA2API.Dog", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Information");

                    b.Property<bool>("IsAdopted");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
